endlessm/eos-shell-content

- data/settings/icon-grid-bn.json.in
Note that we currently have only one subscriptions app for Bengali,
and no encyclopedia, so the Curiosity folder is pretty empty.
https://phabricator.endlessm.com/T13110
> Add icon grid layout for Bengali

- content/Default/apps/content.json
https://phabricator.endlessm.com/T12831
> Add paraguayan constitution app

- bundle/translations.json
- content/Default/apps/content.json
- unzip_content.py
- update_translation_info.py
Include translation info for more apps in translations.json and add a script that can merge them into content.json without using unzip_content.py.
https://phabricator.endlessm.com/T16227
> More translation info

- tools/dh_eoscontent
https://phabricator.endlessm.com/T15856
> Fix missing variable in dh_eoscontent

- debian/control
https://phabricator.endlessm.com/T15856
> Add python3-polib dependency for eos-shell-content-dev

- data/folders/eos-folder-curiosity.directory
- data/folders/eos-folder-games.directory
- data/folders/eos-folder-media.directory
- data/folders/eos-folder-news.directory
- data/folders/eos-folder-social.directory
- data/folders/eos-folder-tools.directory
- data/folders/eos-folder-work.directory
generating folder icons as a mosaic of the contained app icons,
so we no longer need to specify custom folder icons.
https://phabricator.endlessm.com/T17847
> Don't specify custom folder icons

- data/settings/arch-blacklist.json
- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
Also add Get Spotify where it is available. Ban all on ARM
> Add Get VLC and Get Skype to all desktops

- data/settings/icon-grid-es_GT.json.in
Changing to reflect local requests (e.g. most of these devices have codecs and are intended for educational usage)
> Add get dropbox to es_GT layout and reorder

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
- data/settings/icon-grid-zh_CN.json.in
https://phabricator.endlessm.com/T23856
> T23856: migrate 61 legacy eos-apps to flathub

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
- data/settings/icon-grid-zh_CN.json.in
https://phabricator.endlessm.com/T23911
> data/settings/icon-grid: add Aisleriot to Games folder

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
- data/settings/icon-grid-zh_CN.json.in
https://phabricator.endlessm.com/T23935
> data/settings: Add GNOME Chess to the games folder

- content/folders.json
- data/folders/eos-folder-games-to-hack.directory
- data/folders/eos-folder-learn-to-code.directory
- data/settings/arch-blacklist.json
- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
- data/settings/icon-grid-zh_CN.json.in
- data/settings/write-grid-json.py
Add "Games to Hack" and "Learn to Code" folders to desktop. The former is not available on ARM systems, the latter only available on English desktops.
https://phabricator.endlessm.com/T25938
> T25938: feature Endless Studios games and learning apps

- data/settings/arch-blacklist.json
- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
- data/settings/icon-grid-zh_CN.json.in
(on top of https://github.com/endlessm/eos-shell-content/pull/213)
https://phabricator.endlessm.com/T26087
> icon-grid: Add "Get Unity" link to "Games to Hack" folder

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
- data/settings/icon-grid-zh_CN.json.in
This app is very popular during the COVID-19 pandemic and consequent
home-working and home-schooling.
https://phabricator.endlessm.com/T30089
> Add "Get Zoom" launcher to Social folder

- tools/eosshellcontent.py
https://phabricator.endlessm.com/T31311
> eosshellcontent.py: Stop using deprecated/remove method

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-pt.json.in
https://phabricator.endlessm.com/T32693
> icon-grid: Address design feedback

- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-pt.json.in
https://phabricator.endlessm.com/T32693
> icon-grid: Fix KA Kolibri channel id for es, fr, pt

- data/eos-save-icon-grid.in
https://phabricator.endlessm.com/T31616
> T31616 Additional icon grid script updates

- data/settings/icon-grid-C.json.in
https://phabricator.endlessm.com/T34960
> icon grid: Add Gamestar Mechanic

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-ar.json.in
- data/settings/icon-grid-bn.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-id.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-th.json.in
- data/settings/icon-grid-vi.json.in
- data/settings/icon-grid-zh_CN.json.in
It is in first position in all locales, despite only being available in
English and Spanish, for simplicity and consistency.
This is also what we did for English-only Hack in almost all locales.
https://phabricator.endlessm.com/T35096
> Add Endless Key to app grid

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-pt.json.in
https://phabricator.endlessm.com/T32962
> Replace Gedit with Text Editor in default grid layouts

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-pt.json.in
- data/settings/icon-grid-zh_CN.json.in
This change somewhere between GNOME 41 and GNOME 43.
https://phabricator.endlessm.com/T35404
> Update app ID for Settings

- data/settings/icon-grid-C.json.in
- data/settings/icon-grid-es.json.in
- data/settings/icon-grid-es_GT.json.in
- data/settings/icon-grid-fr.json.in
- data/settings/icon-grid-pt.json.in
This new version is a total rewrite with a new app ID.
https://phabricator.endlessm.com/T35401
> Reference Arduino IDE v2 in app grids
