data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-zh_CN.json.in
Due to the way the flatpak directory structure is organized,
the dekstop IDs have a "kde4-" prefix before the app ID.
https://phabricator.endlessm.com/T12968
=> Fix kde desktop IDs on icon grid

bundle/translations.json, content/Default/apps/content.json, unzip_content.py
Update to the latest content.json from the CMS. This includes the new
translation_type and translation_id fields which will be used to add
<translation> tags to the AppData XML files. Only a few of the apps
currently have correct settings, but the keys are needed for the AppData
work to proceed.
I left out some screenshots that were also updated in appstore.zip since they were unrelated to this work.
https://phabricator.endlessm.com/T16227
=> Pull translation info in content.json from CMS

tools/dh_eoscontent
It was a typical copy/paste error.
https://phabricator.endlessm.com/T15856
=> Fix reference when generating the appdata

tools/eos-content-merge
Upstream GNOME apps have started to provide localization
of the icon specification in desktop files as part of
the migration from intltool to gettext, even though
in practice they specify the same icon for all locales.
Let's filter these localized icons out so that the
Endless provided icon is used for all locales.
https://phabricator.endlessm.com/T17971
=> eos-content-merge: Ignore localized icons

data/settings/icon-grid-id.json.in
We have fixed this in the image builder with an -append for 3.2.2, but the correct
fix is to patch it into the ostree and then drop it from the image builder.
https://phabricator.endlessm.com/T18139
=> add first indonesian apps to the grid

.gitignore, Makefile.am, content/Makefile.am, tools/Makefile.am
Various fixes for compatibility with automake 1.15. The primary change is to generate the json.h files in the source directory.
https://phabricator.endlessm.com/T18550
=> Automake 1.15 fixes

data/settings/icon-grid-id.json.in
Now that we've added the apps to the image in https://github.com/endlessm/eos-image-builder/pull/362 we need to make sure that they're on the desktop for people to discover. Other images put these types of apps in the curiosity folder so I'm bringing that back.
=> Add curiosity folder to ID and populate with local apps

data/settings/icon-grid-C.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in
Create curiosity folders for th and vi now that we have wiki apps to populate them.
Add extra options for the C locale to make sure that all the apps we ship in SEA images are visible to the user on the desktop.
=> Update desktop layouts to reflect new apps available for SEA

data/settings/icon-grid-pt.json.in
Here's what the icon grid looks like with this change (on a live session, hence Formatar and Chromium):
https://phabricator.endlessm.com/T20249#521710
=> Add Omelete to pt desktop

tools/dh_eoscontent
dh_eoscontent: Look for appstream data in '/usr/share/{metainfo,appdata}'
Appstream specification defines /usr/share/metainfo as the correct path
to store this type of metainformation [1] and /usr/share/appdata as a
legacy path, so we should look in both instead of just the old one.
[1] https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
https://phabricator.endlessm.com/T20690
=> dh_eoscontent: Look for appstream data in '/usr/share/{metainfo,appdata}'

data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in, data/settings/icon-grid-zh_CN.json.in
Update .desktop links to use the Flatpak version of LibreOffice.
https://phabricator.endlessm.com/T22113
=> icon-grid-*: change to LibreOffice flatpak

data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in, data/settings/icon-grid-zh_CN.json.in
Ensure that .desktop files stored in the kde4 subdirectory are also matched and
migrated too. This was done manually in the eos-image-builder PR but forgotten
here.
https://phabricator.endlessm.com/T23856
=> data/settings: apply migrations to kde4- prefixed apps too

data/Makefile.am, data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in, data/settings/icon-grid-zh_CN.json.in, data/settings/write-grid-json.py
It is not enough to define keys for directories at the top level of the file: they must also be listed in the "desktop" pseudo-directory. Add them there; add a check that would have caught this, and fix the app ID for com.endlessnetwork.MidnightmareTeddy, which has turned out to be CamelCase not lowercase.
https://phabricator.endlessm.com/T25938
https://phabricator.endlessm.com/T26087
=> Add "Games to Hack" and "Learn to Code" to desktop

data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in, data/settings/icon-grid-zh_CN.json.in
Tested by installing all apps, copying `icon-grid-C.json.in` to `/var/lib/eos-image-defaults/icon-grid/icon-grid-C.json`, and running `eos-reset-desktop`.
https://phabricator.endlessm.com/T25938
=> Add Tank Warriors and Missile Math to icon grid

data/settings/icon-grid-C.json.in
I also moved some of them out of Learn to Code since they have nothing to do with coding.
https://phabricator.endlessm.com/T26235
=> icon-grid: add missing Endless Network knowledge apps

data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in
Never existed:
com.endlessm.health.pt
com.endlessm.maternity.pt
Intentionally retired for quality, maintainence or licence reasons:
com.endlessm.video_funny_videos
com.endlessm.omelete.pt
com.endlessm.duet_diary.th
https://phabricator.endlessm.com/T27026
=> data/settings: Remove retired/non-existent apps from icon grids

data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in, data/settings/icon-grid-zh_CN.json.in
Add some new apps which we are going to start shipping by default, and remove some old stuff.
I made the bulk of the modifications to the icon grids programmatically:
https://gist.github.com/wjt/5fff5946a9cc451abb26dc3590f9275d
We have historically maintained each locale's icon grid by hand but I feel like we should be able to do better.
https://phabricator.endlessm.com/T28705
=> Refresh default icon grids

content/Makefile.am
Use automake's `dist_noinst_DATA` primary so that the json.h files get
built with make's default targets and not just `dist`. As before the
files are still distributed so that they wouldn't need to be regenerated
in OBS when a tarball is in use. This allows our transifex tooling to
run a normal checkout prepared with `make` instead of the full `make
distcheck`.
https://phabricator.endlessm.com/T27529
=> build: Make json.h files during normal build

content/Default/apps/content.json
Add the key to any app whose application ID doesn’t start with a
recognisable prefix like `org.gnome.` or `org.kde.`.
eos-build will convert the project-group into an appstream
`<project_group>` tag. See the documentation here:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_group
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T12884
=> content.json: Add project-group key to various GNOME apps

data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in, data/settings/icon-grid-zh_CN.json.in
We will be pre-installing Kolibri and a bunch of content in some
images. Place Kolibri on the desktop, next to the Encyclopedia, or next
to the local curriculum if there is no Encyclopedia.
https://phabricator.endlessm.com/T30160
=> Add Kolibri to default icon grid

download-content
The CMS instance was backed up and terminated. Instead of downloading
the content zip file from the CMS, download the latest version from a
backup in S3.
https://phabricator.endlessm.com/T30127
=> Download the content zip file from S3.

data/eos-save-icon-grid.in
Previously, this script dumped the old `icon-grid-layout` GSettings key
into a JSON file, so that the JSON file could be put into the image
configuration (using the `63-icon-grid` hook in eos-image-builder, which
loads data from JSON files stored in
`endless-image-config.git/data/icon-grid`).
The `icon-grid-layout` key has been removed with the reworking and
upstreaming of the customisable icon grids to gnome-shell. The new icon
grid configuration is stored in `app-picker-layout` and relocatable
schemas below `/org/gnome/desktop/app-folders/folders/`.
Rework this script to load its data from the new icon grid configuration
instead, and convert it to the existing JSON format to be loaded by
eos-image-builder in the same way as before.
The conversion from the new icon grid configuration …
=> eos-save-icon-grid: Rewrite script to read new-style settings

data/eos-save-icon-grid.in, debian/control
This fixes a crash introduced by ede8907.
While I was here I added a missing package dependency.
https://phabricator.endlessm.com/T31616
=> Add missing import in eos-save-icon-grid

data/Makefile.am, data/settings/arch-blacklist.json, data/settings/write-grid-json.py
The keys in arch-blacklist.json are the autotools $(host_cpu) variable.
The only key in that file is "arm". But nowadays we only support 64-bit
ARM, for which $(host_cpu) is "aarch64". So this filter now does
nothing.
It doesn't matter, anyway, because the app grid code in Endless OS 3.9
and later just hides empty folders.
Remove the blacklist logic, which also removes some problematic
terminology from our distro.
While I was here I cleaned the JSON-mangling script a bit. You might notice that it is now a fancy `cat` that performs a tiny amount of validation on the JSON. You might then think – can we just rename all the `.json.in` files to `.json`, install them verbatim, and just syntax-check them at build time? And yes, we could, but I ran out of evening and appetite to think about …
=> icon grid: Remove per-architecture blacklist

data/settings/icon-grid-C.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-pt.json.in
For reasons outlined in https://github.com/endlessm/eos-meta/pull/767 we
are removing Brasero from the base OS.
https://phabricator.endlessm.com/T35003
=> Remove Brasero from default icon grid.

data/settings/icon-grid-C.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-pt.json.in
Organize some game development tools which are being added to the default applications. For now, these will be placed in the Create and Coding Education directories.
https://phabricator.endlessm.com/T34960
-----
See also:
=> icon grid: Add game development tools

data/settings/icon-grid-C.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-pt.json.in
https://phabricator.endlessm.com/T34908
=> Replace Eye of GNOME with Loupe in default app grid layouts

data/settings/icon-grid-C.json.in, data/settings/icon-grid-ar.json.in, data/settings/icon-grid-bn.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-id.json.in, data/settings/icon-grid-pt.json.in, data/settings/icon-grid-th.json.in, data/settings/icon-grid-vi.json.in, data/settings/icon-grid-zh_CN.json.in
Also add Decibels to Utilities folder so it doesn't clutter up the grid, since it's best used to handle opening files but less useful to open on its own.
https://phabricator.endlessm.com/T32696
=> Replace Rhythmbox with Music in default app grid layouts

data/settings/icon-grid-C.json.in, data/settings/icon-grid-es.json.in, data/settings/icon-grid-es_GT.json.in, data/settings/icon-grid-fr.json.in, data/settings/icon-grid-pt.json.in
The change from com.vixalien.decibels to org.gnome.Decibels has been rolled out on Flathub, so change the app grids accordingly.
https://phabricator.endlessm.com/T32696
=> Update Decibels app ID in app grids

data/settings/icon-grid-es.json.in
Move the Weather app's icon from Internet folder into Utilidades folder.
https://phabricator.endlessm.com/T35817
=> icon-grid-es: Move Weather app's icon into Utilidades folder

autogen.sh, debian/eos-acknowledgements.install
The gnome-common [1] provided gnome-autogen.sh is completely deprecated.
To keep it work in the future, we have to do the migration by following GnomeCommon/Migration [2].
[1]: https://gitlab.gnome.org/Archive/gnome-common
[2]: https://wiki.gnome.org/Projects/GnomeCommon/Migration
Fixes: https://github.com/endlessm/eos-build-meta/issues/39
=> autogen.sh: Migrate gnome-autogen.sh
